### Create a new Customer
POST http://localhost:1234/api/customers
Accept: application/json
Content-Type: application/json

{
    "email": "vanitha@gmail.com",
    "name" : "Vanitha Kumari",
    "password": "secret123"
}

### Login
POST http://localhost:1234/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "vanitha@gmail.com",
    "password": "secret123"
}

